name: Sync languages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *" # 12pm daily

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pio
          pip install -r src/requirements.txt

      - name: Execute Python script
        run: python src/main.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Import languages from Wikipedia" --allow-empty)

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
